services:
  eamdj:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
          - ${USER_SECRETS_PATH:-${APPDATA}/Microsoft/UserSecrets}:/home/app/.microsoft/usersecrets:ro
          - ${HTTPS_PATH:-${APPDATA}/ASP.NET/Https}:/home/app/.aspnet/https:ro